#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

#run both allrun scripts in the below folders
./cavitation/1x640/Allclean
./condensation/1x640/Allclean
#------------------------------------------------------------------------------
