#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase

rm -rf CSV dynamicCode 0 *.png
rm -r results
#------------------------------------------------------------------------------
